version: '3.8'
services:
  backend:
    build:
      context: . .
      dockerfile: src/PTA.API/Dockerfile
    ports:
      - '5000:80'
  frontend:
    build:
      context: .
      dockerfile: src/PTA.UI/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend
