name: Deploy to QA (Render)

on:
  push:
    branches: [ 'release/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Deploy Backend to QA
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID_QA_BACKEND }}
          IMAGE: ${{ env.IMAGE_BACKEND }}:${{ github.sha }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "clearCache": true,
              "dockerImage": "'"$IMAGE"'"
            }'
