name: Deploy to UAT (Render)

on:
  push:
    branches: [ uat ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to UAT on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID_UAT_BACKEND }}
          IMAGE: ${{ secrets.IMAGE_BACKEND }}:${{ github.sha }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"clearCache\": true, \"dockerImage\": \"$IMAGE\"}"
